spring:
  application:
    name: accm-people
  datasource:
    url: jdbc:postgresql://localhost:5432/accm
    username: accm
    password: accm
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: people
  flyway:
    enabled: true
    schemas: people
    default-schema: people
  threads:
    virtual:
      enabled: true

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
