spring:
  application:
    name: accm-comicBook
  datasource:
    url: jdbc:postgresql://localhost:5432/accm
    username: accm
    password: accm
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: comicbook
  flyway:
    enabled: true
    schemas: comicbook
    default-schema: comicbook
  threads:
    virtual:
      enabled: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
